use crate::rkp::DeviceInfo;

/// Represents a Certificate Signing Request that is sent to an RKP backend to request
/// certificates to be signed for a set of public keys. The CSR is partially generated by an
/// IRemotelyProvisionedComponent HAL. The set of public keys to be signed is authenticated
/// (signed) with a device-unique key.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Csr {
    /// CSR V2 was introduced in Android T. In this version, the payload is encrypted using
    /// an Endpoint Encryption Key (EEK).
    V2 {
        /// Describes the device that is requesting certificates.
        device_info: DeviceInfo,
    },
    /// CSR V3 was introduced in Android T. This version drops encryption of the payload.
    V3 {
        /// Describes the device that is requesting certificates.
        device_info: DeviceInfo,
    },
}
